apiVersion: v1
kind: ServiceAccount
metadata:
  name: quiz-web
  namespace: quizproject
  labels:
    app.kubernetes.io/name: quiz-web
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: quizproject
automountServiceAccountToken: false
