// The line half of the coverage gate.
//
// Node's own `--test-coverage-lines` cannot be trusted here, and the reason is
// structural rather than a bug anyone can fix from this side. V8 reports byte
// ranges into the code it actually ran — the output of the esbuild transform in
// tests/support/jsx.mts — while the report is written against the file on disk.
// The inline source map closes most of that gap, but only for positions the
// map knows about. A line of the original with no mapping into the generated
// code (a comment, a type-only line, a blank) can never be reported as
// executed, and Node counts it against the total regardless.
//
// The visible effect is a number that moves when prose moves. Measured on
// 2c47d3b, changing nothing but the comment inside one effect in App.tsx:
//
//   no comment                 100.00%
//   one line of comment         99.85%
//   seven lines, short text     99.96%
//   seven lines, longer text    99.78%
//
// Not monotonic, because it was never counting comments — it was mismapping,
// and every edit reshuffles which original lines end up unmapped. A 100%
// threshold on that fails for reasons unrelated to what the tests reach, and
// the way to make it pass is to move the explanation out of the function, which
// is precisely backwards.
//
// So this counts lines the other way round: a line of the original is
// executable if the map puts generated code on it, and covered if any of that
// generated code ran. Lines the map never mentions are not counted at all —
// they are not lines a test could reach. Functions and branches stay with
// Node, which counts those per range and does not have this problem.
import { readFile, readdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { relative } from "node:path";

import { transformSync } from "esbuild";

import { TRANSFORM_OPTIONS, loaderFor } from "../tests/support/jsx.mts";

interface V8Range {
  startOffset: number;
  endOffset: number;
  count: number;
}

interface V8Script {
  url: string;
  functions: { ranges: V8Range[] }[];
}

const BASE64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

/**
 * Decodes one line of a source map's `mappings` field.
 *
 * Only the generated column and the original line are wanted, but the VLQ
 * fields are positional and relative, so every segment has to be walked in full
 * to keep the running totals honest.
 */
function decodeLine(
  line: string,
  state: { originalLine: number }
): { generatedColumn: number; originalLine: number }[] {
  const segments: { generatedColumn: number; originalLine: number }[] = [];
  let generatedColumn = 0;
  for (const segment of line.split(",")) {
    if (!segment) continue;
    const fields: number[] = [];
    let value = 0;
    let shift = 0;
    for (const character of segment) {
      const digit = BASE64.indexOf(character);
      if (digit < 0) throw new Error(`Unreadable source map segment: ${segment}`);
      value += (digit & 31) << shift;
      if (digit & 32) {
        shift += 5;
        continue;
      }
      const negative = value & 1;
      value >>= 1;
      fields.push(negative ? -value : value);
      value = 0;
      shift = 0;
    }
    generatedColumn += fields[0] ?? 0;
    // A one-field segment says "generated code here, from nowhere in
    // particular" — helper code esbuild introduced. It maps to no original
    // line, so it is not this file's to account for.
    if (fields.length < 4) continue;
    state.originalLine += fields[2] ?? 0;
    segments.push({ generatedColumn, originalLine: state.originalLine });
  }
  return segments;
}

/** Every generated position the map ties to a line of the original. */
function decodeMappings(mappings: string): Map<number, { line: number; column: number }[]> {
  const byOriginalLine = new Map<number, { line: number; column: number }[]>();
  const state = { originalLine: 0 };
  mappings.split(";").forEach((line, generatedLine) => {
    for (const segment of decodeLine(line, state)) {
      const positions = byOriginalLine.get(segment.originalLine) ?? [];
      positions.push({ line: generatedLine, column: segment.generatedColumn });
      byOriginalLine.set(segment.originalLine, positions);
    }
  });
  return byOriginalLine;
}

/** Offset of the first character of each line, so positions become offsets. */
function lineOffsets(code: string): number[] {
  const offsets = [0];
  for (let index = 0; index < code.length; index += 1) {
    if (code[index] === "\n") offsets.push(index + 1);
  }
  return offsets;
}

/**
 * Whether the generated byte at `offset` ran.
 *
 * V8 nests its ranges: an uncovered `else` sits inside a covered function. The
 * innermost range that contains the offset is the one that answers.
 */
function covered(ranges: V8Range[], offset: number): boolean {
  let answer = false;
  let narrowest = Infinity;
  for (const range of ranges) {
    if (offset < range.startOffset || offset >= range.endOffset) continue;
    const width = range.endOffset - range.startOffset;
    if (width > narrowest) continue;
    narrowest = width;
    answer = range.count > 0;
  }
  return answer;
}

const coverageDir = process.argv[2];
const threshold = Number(process.argv[3] ?? "100");
if (!coverageDir) throw new Error("usage: coverage-lines.mts <NODE_V8_COVERAGE dir> [threshold]");

const root = new URL("../", import.meta.url);
const sourcePrefix = new URL("src/", root).href;

// One coverage file is written per test process, and the suite runs several.
// Each is kept separate rather than merged, because V8 does not draw the same
// ranges in every process: a path one process never took can be reported there
// as a narrower zero-count range starting at the same offset as the covering
// range another process recorded. Merged into one list, the narrower zero wins
// and a line that demonstrably ran — api.ts's request timeout, which
// api.test.ts asserts on — reads as missed. A line reached in any process is
// reached, so the per-process answers are unioned instead.
const rangesByUrl = new Map<string, V8Range[][]>();
for (const entry of await readdir(coverageDir)) {
  if (!entry.endsWith(".json")) continue;
  const report = JSON.parse(await readFile(`${coverageDir}/${entry}`, "utf8")) as { result: V8Script[] };
  for (const script of report.result) {
    if (!script.url.startsWith(sourcePrefix)) continue;
    const perProcess = rangesByUrl.get(script.url) ?? [];
    perProcess.push(script.functions.flatMap(fn => fn.ranges));
    rangesByUrl.set(script.url, perProcess);
  }
}

if (rangesByUrl.size === 0) {
  throw new Error(`No coverage for ${sourcePrefix} in ${coverageDir}. Did the suite run?`);
}

let totalExecutable = 0;
let totalCovered = 0;
const shortfalls: string[] = [];

for (const url of [...rangesByUrl.keys()].sort()) {
  const perProcess = rangesByUrl.get(url)!;
  const loader = loaderFor(url);
  if (loader === null) continue;

  const source = await readFile(fileURLToPath(url), "utf8");
  // sourcemap: true rather than "inline" only moves where the map is returned.
  // The generated code ahead of it — every offset V8 reported — is identical.
  const { code, map } = transformSync(source, {
    ...TRANSFORM_OPTIONS,
    loader,
    sourcemap: true,
    sourcefile: url
  });
  const offsets = lineOffsets(code);
  const positionsByLine = decodeMappings((JSON.parse(map) as { mappings: string }).mappings);

  const missed: number[] = [];
  for (const [originalLine, positions] of positionsByLine) {
    totalExecutable += 1;
    const reached = positions.some(position => {
      const lineStart = offsets[position.line];
      if (lineStart === undefined) return false;
      const offset = lineStart + position.column;
      return perProcess.some(ranges => covered(ranges, offset));
    });
    if (reached) totalCovered += 1;
    else missed.push(originalLine + 1);
  }

  if (missed.length > 0) {
    const listed = missed.sort((a, b) => a - b).join(", ");
    shortfalls.push(`  ${relative(fileURLToPath(root), fileURLToPath(url))}: ${listed}`);
  }
}

const percentage = (totalCovered / totalExecutable) * 100;
const rounded = Math.round(percentage * 100) / 100;
console.log(`line coverage ${rounded.toFixed(2)}% — ${totalCovered}/${totalExecutable} mapped lines`);

if (shortfalls.length > 0) {
  console.log("lines with generated code that never ran:");
  for (const shortfall of shortfalls) console.log(shortfall);
}

if (rounded < threshold) {
  console.error(`Error: ${rounded.toFixed(2)}% line coverage does not meet threshold of ${threshold}%.`);
  process.exit(1);
}
